language: bash
before_install: sudo apt-get install python-tk

language: python
python: 3.6
install: python setup -t

services:
  - xvfb

before_script:
  - "export DISPLAY=:99.0"
  - sleep 3 # give xvfb some time to start

script: ./run
