language: bash
before_install: sudo apt-get install python-tk

language: python
python: 2.7
install: python2 setup -t

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: ./run
